modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="firstmod" #mandatory

version="1.16.3-1.0.0" #mandatory

displayName="First Mod" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Thanks for this example mod goes to Java" #optional

authors="Regnegade" #optional

description='''
First mod built by Regnegade - Regular Renegade
'''

[[dependencies.examplemod]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[34,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
